# Generated by Django 4.0.3 on 2022-08-01 14:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock_name', models.CharField(max_length=200)),
                ('stock_url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
