# Generated by Django 4.0.3 on 2022-08-01 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocks',
            options={'ordering': ['stock_name']},
        ),
    ]
